language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - android-30
    - build-tools-30.0.2
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'
